---
  - name: Install dependencies
    yum: 
      name: "{{ item }}"
      state: present
    with_items: 
      - httpd-devel 
      - apr 
      - apr-devel 
      - apr-util 
      - apr-util-devel 
      - gcc 
      - make 
      - libtool 
      - autoconf

  - name: Restart Apache
    service: 
      name: httpd 
      state: restarted