apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: web-go
spec:
  containers:
  - name: curl
    image: radial/busyboxplus:curl
    command: ["sh","-c","sleep 99999999999"]
    resources:
      requests:
        memory: "600Mi"
        cpu: "400m"
      limits:
        memory: "800Mi"
        cpu: "800m"
    ports:
    - containerPort: 80